name: Hoogii Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out Hoogii's bug report!
        We can't guarantee when your problem will be fixed, but we will do our best to fix every bug report.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?(Email or Discord)
      placeholder: ex. email@example.com, hello#1234
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Please tell us what happened and what you expected to happen.
      placeholder: Tell us what you see!
      value: "A bug happened while I was..."
    validations:
      required: true
  - type: textarea
    id: waht-you-expected
    attributes:
      label: What you expected?
      description: Please tell us what you expected to happen.
      placeholder: Tell us what you expected to happen!
      value: "I expected... to happen while I was..."
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of Hoogii are you running? <a href="https://chrome.google.com/webstore/detail/hoogii-wallet/jljjeghmeihjegifdhbghcoihdiegkkl%22%3E">Check the current version here</a>
      placeholder: ex. v0.0.8
    validations:
      required: true
  - type: dropdown
    id: device
    attributes:
      label: What system are you seeing the problem on?
      multiple: true
      options: 
      - macOS
      - Windows
      - Linux
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
  - type: markdown
    attributes:
      value: |
        Thank you for your great suggestion, welcome to join our <a href="https://discord.com/invite/eQkGXgprvn">Discord</a> and follow our latest news and updates!
